/**
 * ©2026 Commerce Layer Inc.
 * Source code generated automatically by SDK codegen
 **/
/** biome-ignore-all lint/correctness/noUnusedImports: this file is autogenerated */

import { isDeepStrictEqual } from 'node:util'
import { beforeAll, describe, expect, test } from 'vitest'
import { type CommerceLayerClient, type OrderValidationRule, order_validation_rules } from '../../src'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {
  CommonData,
  checkCommon,
  checkCommonData,
  checkCommonParams,
  checkCommonParamsList,
  currentAccessToken,
  getClient,
  handleError,
  interceptRequest,
  randomValue,
  TestData,
} from '../../test/common'

let cl: CommerceLayerClient

beforeAll(async () => {
  cl = await getClient()
})

describe('OrderValidationRules resource', () => {
  const resourceType = 'order_validation_rules'
  const resourcePath = 'order_validation_rules'

  /* spec.retrieve.start */
  test(resourceType + '.retrieve', async () => {
    const id = TestData.id
    const params = { fields: { [resourceType]: CommonData.paramsFields } }

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await order_validation_rules
      .retrieve(id, params, CommonData.options)
      .then((res: OrderValidationRule) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.retrieve.stop */

  /* spec.list.start */
  test(resourceType + '.list', async () => {
    const params = CommonData.paramsList

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath)
      checkCommonParamsList(request, params)
      return interceptRequest()
    })

    await order_validation_rules
      .list(params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.list.stop */

  /* spec.type.start */
  test(resourceType + '.type', async () => {
    const resource = { id: TestData.id, type: resourceType }
    expect(order_validation_rules.isOrderValidationRule(resource)).toBeTruthy()

    const type = order_validation_rules.type()
    expect(type).toBe(resourceType)
  })
  /* spec.type.stop */

  /* spec.relationship.start */
  test(resourceType + '.relationship', async () => {
    const relId = order_validation_rules.relationship(TestData.id)
    expect(isDeepStrictEqual(relId, { id: TestData.id, type: resourceType }))

    const relResId = order_validation_rules.relationship({ id: TestData.id, type: resourceType })
    expect(isDeepStrictEqual(relResId, { id: TestData.id, type: resourceType }))
  })
  /* spec.relationship.stop */

  /* spec.parse.start */
  /*
  test(resourceType + '.parse', async () => {

    const reference = 'myReferenceId'

    const payload = `
    {
	    "data": {
        "id": "AbcdEfgHiL",
        "meta": {
          "mode": "test",
          "organization_id": "myOrgId"
        },
        "type": "${resourceType}",
        "links": {
          "self": "https://sdk-test-org.commercelayer.io/api/${resourceType}/AbcdEfgHiL"
        },
        "attributes": {
          "metadata": {},
          "reference": "${reference}",
          "created_at": "2023-10-01T05:53:29.296Z",
          "updated_at": "2023-10-10T08:52:13.251Z"
        }
      }
    }
    `

    const res = order_validation_rules.parse(payload) as OrderValidationRule

    expect(res.type).toBe(resourceType)
    expect(res.reference).toBe(reference)

  })
  */
  /* spec.parse.stop */

  /* spec.instance start */
  test(resourceType + '.instance', async () => {
    expect(order_validation_rules)
    expect(order_validation_rules.type()).toBe(resourceType)
  })
  /* spec.instance stop */

  /* relationship.market start */
  test(resourceType + '.market', async () => {
    const id = TestData.id
    const params = { fields: { markets: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'market')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await order_validation_rules
      .market(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.market stop */

  /* relationship.attachments start */
  test(resourceType + '.attachments', async () => {
    const id = TestData.id
    const params = { fields: { attachments: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'attachments')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await order_validation_rules
      .attachments(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.attachments stop */

  /* relationship.event_stores start */
  test(resourceType + '.event_stores', async () => {
    const id = TestData.id
    const params = { fields: { event_stores: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'event_stores')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await order_validation_rules
      .event_stores(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.event_stores stop */
})
