/**
 * ©2026 Commerce Layer Inc.
 * Source code generated automatically by SDK codegen
 **/
/** biome-ignore-all lint/correctness/noUnusedImports: this file is autogenerated */

import { isDeepStrictEqual } from 'node:util'
import { beforeAll, describe, expect, test } from 'vitest'
import { type CommerceLayerClient, orders, type PaymentLink, payment_links, payment_settings } from '../../src'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {
  CommonData,
  checkCommon,
  checkCommonData,
  checkCommonParams,
  checkCommonParamsList,
  currentAccessToken,
  getClient,
  handleError,
  interceptRequest,
  randomValue,
  TestData,
} from '../../test/common'

let cl: CommerceLayerClient

beforeAll(async () => {
  cl = await getClient()
})

describe('PaymentLinks resource', () => {
  const resourceType = 'payment_links'
  const resourcePath = 'payment_links'

  /* spec.create.start */
  test(resourceType + '.create', async () => {
    const createAttributes = {
      url: randomValue('string', 'url'),
      return_url: randomValue('string', 'return_url'),
      order: orders.relationship(TestData.id),
      payment_setting: payment_settings.relationship(TestData.id),
    }

    const attributes = { ...createAttributes, reference: TestData.reference }
    const params = { fields: { [resourceType]: CommonData.paramsFields } }
    const resData = attributes

    cl.addRequestInterceptor((request) => {
      const data = JSON.parse(String(request.options.body))
      expect(request.options.method).toBe('POST')
      checkCommon(request, resourcePath)
      checkCommonData(data, resourceType, attributes)
      expect(payment_links.isPaymentLink(data.data)).toBeTruthy()
      return interceptRequest()
    })

    await payment_links
      .create(resData, params, CommonData.options)
      .then((res: PaymentLink) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.create.stop */

  /* spec.retrieve.start */
  test(resourceType + '.retrieve', async () => {
    const id = TestData.id
    const params = { fields: { [resourceType]: CommonData.paramsFields } }

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .retrieve(id, params, CommonData.options)
      .then((res: PaymentLink) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.retrieve.stop */

  /* spec.update.start */
  test(resourceType + '.update', async () => {
    const attributes = { reference_origin: TestData.reference_origin, metadata: TestData.metadata }
    const params = { fields: { [resourceType]: CommonData.paramsFields } }
    const resData = { id: TestData.id, ...attributes }

    cl.addRequestInterceptor((request) => {
      const data = JSON.parse(String(request.options.body))
      expect(request.options.method).toBe('PATCH')
      checkCommon(request, resourcePath, resData.id, currentAccessToken)
      checkCommonData(data, resourceType, attributes, resData.id)
      return interceptRequest()
    })

    await payment_links
      .update(resData, params, CommonData.options)
      .then((res: PaymentLink) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.update.stop */

  /* spec.delete.start */
  test(resourceType + '.delete', async () => {
    const id = TestData.id

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('DELETE')
      checkCommon(request, resourcePath, id, currentAccessToken)
      return interceptRequest()
    })

    await payment_links
      .delete(id, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.delete.stop */

  /* spec.list.start */
  test(resourceType + '.list', async () => {
    const params = CommonData.paramsList

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath)
      checkCommonParamsList(request, params)
      return interceptRequest()
    })

    await payment_links
      .list(params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.list.stop */

  /* spec.type.start */
  test(resourceType + '.type', async () => {
    const resource = { id: TestData.id, type: resourceType }
    expect(payment_links.isPaymentLink(resource)).toBeTruthy()

    const type = payment_links.type()
    expect(type).toBe(resourceType)
  })
  /* spec.type.stop */

  /* spec.relationship.start */
  test(resourceType + '.relationship', async () => {
    const relId = payment_links.relationship(TestData.id)
    expect(isDeepStrictEqual(relId, { id: TestData.id, type: resourceType }))

    const relResId = payment_links.relationship({ id: TestData.id, type: resourceType })
    expect(isDeepStrictEqual(relResId, { id: TestData.id, type: resourceType }))
  })
  /* spec.relationship.stop */

  /* spec.parse.start */
  /*
  test(resourceType + '.parse', async () => {

    const reference = 'myReferenceId'

    const payload = `
    {
	    "data": {
        "id": "AbcdEfgHiL",
        "meta": {
          "mode": "test",
          "organization_id": "myOrgId"
        },
        "type": "${resourceType}",
        "links": {
          "self": "https://sdk-test-org.commercelayer.io/api/${resourceType}/AbcdEfgHiL"
        },
        "attributes": {
          "metadata": {},
          "reference": "${reference}",
          "created_at": "2023-10-01T05:53:29.296Z",
          "updated_at": "2023-10-10T08:52:13.251Z"
        }
      }
    }
    `

    const res = payment_links.parse(payload) as PaymentLink

    expect(res.type).toBe(resourceType)
    expect(res.reference).toBe(reference)

  })
  */
  /* spec.parse.stop */

  /* spec.instance start */
  test(resourceType + '.instance', async () => {
    expect(payment_links)
    expect(payment_links.type()).toBe(resourceType)
  })
  /* spec.instance stop */

  /* relationship.order start */
  test(resourceType + '.order', async () => {
    const id = TestData.id
    const params = { fields: { orders: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'order')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .order(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.order stop */

  /* relationship.payment_setting start */
  test(resourceType + '.payment_setting', async () => {
    const id = TestData.id
    const params = { fields: { payment_settings: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_setting')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .payment_setting(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_setting stop */

  /* relationship.payment_session start */
  test(resourceType + '.payment_session', async () => {
    const id = TestData.id
    const params = { fields: { payment_sessions: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_session')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .payment_session(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_session stop */

  /* relationship.attachments start */
  test(resourceType + '.attachments', async () => {
    const id = TestData.id
    const params = { fields: { attachments: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'attachments')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .attachments(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.attachments stop */

  /* relationship.events start */
  test(resourceType + '.events', async () => {
    const id = TestData.id
    const params = { fields: { events: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'events')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .events(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.events stop */

  /* relationship.event_stores start */
  test(resourceType + '.event_stores', async () => {
    const id = TestData.id
    const params = { fields: { event_stores: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'event_stores')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_links
      .event_stores(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.event_stores stop */

  /* trigger._refresh start */
  test(resourceType + '._refresh', async () => {
    let triggerAttr = '_refresh'
    if (!triggerAttr.startsWith('_')) triggerAttr = `_${triggerAttr}`

    const triggerValue = true
    const attributes = { [triggerAttr]: triggerValue }
    const id = TestData.id

    const _intId = cl.addRequestInterceptor((request) => {
      const data = JSON.parse(String(request.options.body))
      expect(request.options.method).toBe('PATCH')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonData(data, resourceType, attributes, id)
      return interceptRequest()
    })

    await payment_links
      ._refresh(id, {}, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* trigger._refresh stop */

  /* trigger._cancel start */
  test(resourceType + '._cancel', async () => {
    let triggerAttr = '_cancel'
    if (!triggerAttr.startsWith('_')) triggerAttr = `_${triggerAttr}`

    const triggerValue = true
    const attributes = { [triggerAttr]: triggerValue }
    const id = TestData.id

    const _intId = cl.addRequestInterceptor((request) => {
      const data = JSON.parse(String(request.options.body))
      expect(request.options.method).toBe('PATCH')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonData(data, resourceType, attributes, id)
      return interceptRequest()
    })

    await payment_links
      ._cancel(id, {}, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* trigger._cancel stop */
})
