/**
 * ©2026 Commerce Layer Inc.
 * Source code generated automatically by SDK codegen
 **/
/** biome-ignore-all lint/correctness/noUnusedImports: this file is autogenerated */

import { isDeepStrictEqual } from 'node:util'
import { beforeAll, describe, expect, test } from 'vitest'
import { type CommerceLayerClient, type PaymentSetting, payment_settings } from '../../src'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {
  CommonData,
  checkCommon,
  checkCommonData,
  checkCommonParams,
  checkCommonParamsList,
  currentAccessToken,
  getClient,
  handleError,
  interceptRequest,
  randomValue,
  TestData,
} from '../../test/common'

let cl: CommerceLayerClient

beforeAll(async () => {
  cl = await getClient()
})

describe('PaymentSettings resource', () => {
  const resourceType = 'payment_settings'
  const resourcePath = 'payment_settings'

  /* spec.retrieve.start */
  test(resourceType + '.retrieve', async () => {
    const id = TestData.id
    const params = { fields: { [resourceType]: CommonData.paramsFields } }

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .retrieve(id, params, CommonData.options)
      .then((res: PaymentSetting) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.retrieve.stop */

  /* spec.list.start */
  test(resourceType + '.list', async () => {
    const params = CommonData.paramsList

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath)
      checkCommonParamsList(request, params)
      return interceptRequest()
    })

    await payment_settings
      .list(params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.list.stop */

  /* spec.type.start */
  test(resourceType + '.type', async () => {
    const resource = { id: TestData.id, type: resourceType }
    expect(payment_settings.isPaymentSetting(resource)).toBeTruthy()

    const type = payment_settings.type()
    expect(type).toBe(resourceType)
  })
  /* spec.type.stop */

  /* spec.relationship.start */
  test(resourceType + '.relationship', async () => {
    const relId = payment_settings.relationship(TestData.id)
    expect(isDeepStrictEqual(relId, { id: TestData.id, type: resourceType }))

    const relResId = payment_settings.relationship({ id: TestData.id, type: resourceType })
    expect(isDeepStrictEqual(relResId, { id: TestData.id, type: resourceType }))
  })
  /* spec.relationship.stop */

  /* spec.parse.start */
  /*
  test(resourceType + '.parse', async () => {

    const reference = 'myReferenceId'

    const payload = `
    {
	    "data": {
        "id": "AbcdEfgHiL",
        "meta": {
          "mode": "test",
          "organization_id": "myOrgId"
        },
        "type": "${resourceType}",
        "links": {
          "self": "https://sdk-test-org.commercelayer.io/api/${resourceType}/AbcdEfgHiL"
        },
        "attributes": {
          "metadata": {},
          "reference": "${reference}",
          "created_at": "2023-10-01T05:53:29.296Z",
          "updated_at": "2023-10-10T08:52:13.251Z"
        }
      }
    }
    `

    const res = payment_settings.parse(payload) as PaymentSetting

    expect(res.type).toBe(resourceType)
    expect(res.reference).toBe(reference)

  })
  */
  /* spec.parse.stop */

  /* spec.instance start */
  test(resourceType + '.instance', async () => {
    expect(payment_settings)
    expect(payment_settings.type()).toBe(resourceType)
  })
  /* spec.instance stop */

  /* relationship.payment_links start */
  test(resourceType + '.payment_links', async () => {
    const id = TestData.id
    const params = { fields: { payment_links: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_links')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .payment_links(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_links stop */

  /* relationship.payment_sessions start */
  test(resourceType + '.payment_sessions', async () => {
    const id = TestData.id
    const params = { fields: { payment_sessions: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_sessions')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .payment_sessions(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_sessions stop */

  /* relationship.payment_transactions start */
  test(resourceType + '.payment_transactions', async () => {
    const id = TestData.id
    const params = { fields: { payment_transactions: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_transactions')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .payment_transactions(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_transactions stop */

  /* relationship.payment_wallets start */
  test(resourceType + '.payment_wallets', async () => {
    const id = TestData.id
    const params = { fields: { payment_wallets: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'payment_wallets')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .payment_wallets(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.payment_wallets stop */

  /* relationship.order_subscriptions start */
  test(resourceType + '.order_subscriptions', async () => {
    const id = TestData.id
    const params = { fields: { order_subscriptions: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'order_subscriptions')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .order_subscriptions(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.order_subscriptions stop */

  /* relationship.event_stores start */
  test(resourceType + '.event_stores', async () => {
    const id = TestData.id
    const params = { fields: { event_stores: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'event_stores')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await payment_settings
      .event_stores(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.event_stores stop */
})
