import type { QueryParamsList, QueryParamsRetrieve } from '../query'
import type {
  ListResponse,
  Resource,
  ResourceCreate,
  ResourceId,
  ResourceRel,
  ResourceSort,
  /* ResourceFilter */ ResourcesConfig,
  ResourceUpdate,
} from '../resource'
import { ApiResource } from '../resource'
import type { EventStore } from './event_stores'
import type { OrderSubscription } from './order_subscriptions'
import type { PaymentLink } from './payment_links'
import type { PaymentSession } from './payment_sessions'
import type { PaymentTransaction } from './payment_transactions'
import type { PaymentWallet } from './payment_wallets'

type PaymentSettingAdyenType = 'payment_setting_adyens'
type PaymentSettingAdyenRel = ResourceRel & { type: PaymentSettingAdyenType }

export type PaymentSettingAdyenSort = Pick<PaymentSettingAdyen, 'id' | 'name' | 'disabled_at'> & ResourceSort
// export type PaymentSettingAdyenFilter = Pick<PaymentSettingAdyen, 'id' | 'gateway_version' | 'auto_capture' | 'name' | 'disabled_at'> & ResourceFilter

interface PaymentSettingAdyen extends Resource {
  readonly type: PaymentSettingAdyenType

  /**
   * The gateway version of the payment setting (external API version).
   * @example ```"2025-09-30.clover"```
   */
  gateway_version?: string | null
  /**
   * The internal versions of the payment setting for payload changes.
   * @example ```{"payment_intent":"V1","setup_intent":"V3"}```
   */
  internal_versions?: Record<string, any> | null
  /**
   * Send this attribute if you want the payment to be automatically captured when authorized.
   */
  auto_capture?: boolean | null
  /**
   * The name of the payment setting.
   * @example ```"Stripe"```
   */
  name?: string | null
  /**
   * Time at which this resource was disabled.
   * @example ```"2018-01-01T12:00:00.000Z"```
   */
  disabled_at?: string | null
  /**
   * The public key linked to your API credential.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  public_key?: string | null
  /**
   * The prefix of the endpoint used for live transactions.
   * @example ```"1797a841fbb37ca7-AdyenDemo"```
   */
  live_url_prefix: string
  /**
   * The gateway webhook endpoint secret, generated by Adyen customer area.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  webhook_endpoint_secret: string
  /**
   * The gateway webhook URL, generated automatically.
   * @example ```"https://core.commercelayer.co/webhook_callbacks/adyen_gateways/xxxxx"```
   */
  webhook_endpoint_url?: string | null

  payment_links?: PaymentLink[] | null
  payment_sessions?: PaymentSession[] | null
  payment_transactions?: PaymentTransaction[] | null
  payment_wallets?: PaymentWallet[] | null
  order_subscriptions?: OrderSubscription[] | null
  event_stores?: EventStore[] | null
}

interface PaymentSettingAdyenCreate extends ResourceCreate {
  /**
   * The gateway version of the payment setting (external API version).
   * @example ```"2025-09-30.clover"```
   */
  gateway_version?: string | null
  /**
   * Send this attribute if you want the payment to be automatically captured when authorized.
   */
  auto_capture?: boolean | null
  /**
   * The name of the payment setting.
   * @example ```"Stripe"```
   */
  name?: string | null
  /**
   * Send this attribute if you want to mark this resource as disabled.
   * @example ```true```
   */
  _disable?: boolean | null
  /**
   * Send this attribute if you want to mark this resource as enabled.
   * @example ```true```
   */
  _enable?: boolean | null
  /**
   * Send this attribute if you want to validate the payment gateway credentials using the gateway’s own APIs.
   * @example ```true```
   */
  _check?: boolean | null
  /**
   * The gateway merchant account.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  merchant_account: string
  /**
   * The gateway API key.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  api_key: string
  /**
   * The public key linked to your API credential.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  public_key?: string | null
  /**
   * The prefix of the endpoint used for live transactions.
   * @example ```"1797a841fbb37ca7-AdyenDemo"```
   */
  live_url_prefix: string
  /**
   * The gateway webhook endpoint secret, generated by Adyen customer area.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  webhook_endpoint_secret: string
}

interface PaymentSettingAdyenUpdate extends ResourceUpdate {
  /**
   * The gateway version of the payment setting (external API version).
   * @example ```"2025-09-30.clover"```
   */
  gateway_version?: string | null
  /**
   * Send this attribute if you want the payment to be automatically captured when authorized.
   */
  auto_capture?: boolean | null
  /**
   * The name of the payment setting.
   * @example ```"Stripe"```
   */
  name?: string | null
  /**
   * Send this attribute if you want to mark this resource as disabled.
   * @example ```true```
   */
  _disable?: boolean | null
  /**
   * Send this attribute if you want to mark this resource as enabled.
   * @example ```true```
   */
  _enable?: boolean | null
  /**
   * Send this attribute if you want to validate the payment gateway credentials using the gateway’s own APIs.
   * @example ```true```
   */
  _check?: boolean | null
  /**
   * The gateway merchant account.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  merchant_account?: string | null
  /**
   * The gateway API key.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  api_key?: string | null
  /**
   * The public key linked to your API credential.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  public_key?: string | null
  /**
   * The prefix of the endpoint used for live transactions.
   * @example ```"1797a841fbb37ca7-AdyenDemo"```
   */
  live_url_prefix?: string | null
  /**
   * The gateway webhook endpoint secret, generated by Adyen customer area.
   * @example ```"xxxx-yyyy-zzzz"```
   */
  webhook_endpoint_secret?: string | null
}

class PaymentSettingAdyens extends ApiResource<PaymentSettingAdyen> {
  static readonly TYPE: PaymentSettingAdyenType = 'payment_setting_adyens' as const

  async create(
    resource: PaymentSettingAdyenCreate,
    params?: QueryParamsRetrieve<PaymentSettingAdyen>,
    options?: ResourcesConfig,
  ): Promise<PaymentSettingAdyen> {
    return this.resources.create<PaymentSettingAdyenCreate, PaymentSettingAdyen>(
      { ...resource, type: PaymentSettingAdyens.TYPE },
      params,
      options,
    )
  }

  async update(
    resource: PaymentSettingAdyenUpdate,
    params?: QueryParamsRetrieve<PaymentSettingAdyen>,
    options?: ResourcesConfig,
  ): Promise<PaymentSettingAdyen> {
    return this.resources.update<PaymentSettingAdyenUpdate, PaymentSettingAdyen>(
      { ...resource, type: PaymentSettingAdyens.TYPE },
      params,
      options,
    )
  }

  async delete(id: string | ResourceId, options?: ResourcesConfig): Promise<void> {
    await this.resources.delete(typeof id === 'string' ? { id, type: PaymentSettingAdyens.TYPE } : id, options)
  }

  async payment_links(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<PaymentLink>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<PaymentLink>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<PaymentLink>(
      { type: 'payment_links' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/payment_links`,
      params,
      options,
    ) as unknown as ListResponse<PaymentLink>
  }

  async payment_sessions(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<PaymentSession>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<PaymentSession>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<PaymentSession>(
      { type: 'payment_sessions' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/payment_sessions`,
      params,
      options,
    ) as unknown as ListResponse<PaymentSession>
  }

  async payment_transactions(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<PaymentTransaction>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<PaymentTransaction>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<PaymentTransaction>(
      { type: 'payment_transactions' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/payment_transactions`,
      params,
      options,
    ) as unknown as ListResponse<PaymentTransaction>
  }

  async payment_wallets(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<PaymentWallet>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<PaymentWallet>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<PaymentWallet>(
      { type: 'payment_wallets' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/payment_wallets`,
      params,
      options,
    ) as unknown as ListResponse<PaymentWallet>
  }

  async order_subscriptions(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<OrderSubscription>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<OrderSubscription>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<OrderSubscription>(
      { type: 'order_subscriptions' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/order_subscriptions`,
      params,
      options,
    ) as unknown as ListResponse<OrderSubscription>
  }

  async event_stores(
    paymentSettingAdyenId: string | PaymentSettingAdyen,
    params?: QueryParamsList<EventStore>,
    options?: ResourcesConfig,
  ): Promise<ListResponse<EventStore>> {
    const _paymentSettingAdyenId =
      (paymentSettingAdyenId as PaymentSettingAdyen).id || (paymentSettingAdyenId as string)
    return this.resources.fetch<EventStore>(
      { type: 'event_stores' },
      `payment_setting_adyens/${_paymentSettingAdyenId}/event_stores`,
      params,
      options,
    ) as unknown as ListResponse<EventStore>
  }

  async _disable(
    id: string | PaymentSettingAdyen,
    params?: QueryParamsRetrieve<PaymentSettingAdyen>,
    options?: ResourcesConfig,
  ): Promise<PaymentSettingAdyen> {
    return this.resources.update<PaymentSettingAdyenUpdate, PaymentSettingAdyen>(
      { id: typeof id === 'string' ? id : id.id, type: PaymentSettingAdyens.TYPE, _disable: true },
      params,
      options,
    )
  }

  async _enable(
    id: string | PaymentSettingAdyen,
    params?: QueryParamsRetrieve<PaymentSettingAdyen>,
    options?: ResourcesConfig,
  ): Promise<PaymentSettingAdyen> {
    return this.resources.update<PaymentSettingAdyenUpdate, PaymentSettingAdyen>(
      { id: typeof id === 'string' ? id : id.id, type: PaymentSettingAdyens.TYPE, _enable: true },
      params,
      options,
    )
  }

  async _check(
    id: string | PaymentSettingAdyen,
    params?: QueryParamsRetrieve<PaymentSettingAdyen>,
    options?: ResourcesConfig,
  ): Promise<PaymentSettingAdyen> {
    return this.resources.update<PaymentSettingAdyenUpdate, PaymentSettingAdyen>(
      { id: typeof id === 'string' ? id : id.id, type: PaymentSettingAdyens.TYPE, _check: true },
      params,
      options,
    )
  }

  isPaymentSettingAdyen(resource: any): resource is PaymentSettingAdyen {
    return resource.type && resource.type === PaymentSettingAdyens.TYPE
  }

  relationship(id: string | ResourceId | null): PaymentSettingAdyenRel {
    return super.relationshipOneToOne<PaymentSettingAdyenRel>(id)
  }

  relationshipToMany(...ids: string[]): PaymentSettingAdyenRel[] {
    return super.relationshipOneToMany<PaymentSettingAdyenRel>(...ids)
  }

  type(): PaymentSettingAdyenType {
    return PaymentSettingAdyens.TYPE
  }
}

const instance = new PaymentSettingAdyens()
export default instance

export type {
  PaymentSettingAdyen,
  PaymentSettingAdyenCreate,
  PaymentSettingAdyens,
  PaymentSettingAdyenType,
  PaymentSettingAdyenUpdate,
}
