/**
 * ©2026 Commerce Layer Inc.
 * Source code generated automatically by SDK codegen
 **/
/** biome-ignore-all lint/correctness/noUnusedImports: this file is autogenerated */

import { isDeepStrictEqual } from 'node:util'
import { beforeAll, describe, expect, test } from 'vitest'
import { type CommerceLayerSingleClient, type ShipmentLineItem, shipment_line_items } from '../../src/single-client'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {
  CommonData,
  checkCommon,
  checkCommonData,
  checkCommonParams,
  checkCommonParamsList,
  currentAccessToken,
  getClient,
  handleError,
  interceptRequest,
  randomValue,
  TestData,
} from '../../test/common'

let cl: CommerceLayerSingleClient

beforeAll(async () => {
  cl = await getClient()
})

describe('ShipmentLineItems resource', () => {
  const resourceType = 'shipment_line_items'
  const resourcePath = 'shipment_line_items'

  /* spec.retrieve.start */
  test(resourceType + '.retrieve', async () => {
    const id = TestData.id
    const params = { fields: { [resourceType]: CommonData.paramsFields } }

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken)
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .retrieve(id, params, CommonData.options)
      .then((res: ShipmentLineItem) => expect(res).not.toBeNull())
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.retrieve.stop */

  /* spec.list.start */
  test(resourceType + '.list', async () => {
    const params = CommonData.paramsList

    cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath)
      checkCommonParamsList(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .list(params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* spec.list.stop */

  /* spec.type.start */
  test(resourceType + '.type', async () => {
    const resource = { id: TestData.id, type: resourceType }
    expect(shipment_line_items.isShipmentLineItem(resource)).toBeTruthy()

    const type = shipment_line_items.type()
    expect(type).toBe(resourceType)
  })
  /* spec.type.stop */

  /* spec.relationship.start */
  test(resourceType + '.relationship', async () => {
    const relId = shipment_line_items.relationship(TestData.id)
    expect(isDeepStrictEqual(relId, { id: TestData.id, type: resourceType }))

    const relResId = shipment_line_items.relationship({ id: TestData.id, type: resourceType })
    expect(isDeepStrictEqual(relResId, { id: TestData.id, type: resourceType }))
  })
  /* spec.relationship.stop */

  /* spec.parse.start */
  /*
  test(resourceType + '.parse', async () => {

    const reference = 'myReferenceId'

    const payload = `
    {
	    "data": {
        "id": "AbcdEfgHiL",
        "meta": {
          "mode": "test",
          "organization_id": "myOrgId"
        },
        "type": "${resourceType}",
        "links": {
          "self": "https://sdk-test-org.commercelayer.io/api/${resourceType}/AbcdEfgHiL"
        },
        "attributes": {
          "metadata": {},
          "reference": "${reference}",
          "created_at": "2023-10-01T05:53:29.296Z",
          "updated_at": "2023-10-10T08:52:13.251Z"
        }
      }
    }
    `

    const res = shipment_line_items.parse(payload) as ShipmentLineItem

    expect(res.type).toBe(resourceType)
    expect(res.reference).toBe(reference)

  })
  */
  /* spec.parse.stop */

  /* spec.instance start */
  test(resourceType + '.instance', async () => {
    expect(shipment_line_items)
    expect(shipment_line_items.type()).toBe(resourceType)
  })
  /* spec.instance stop */

  /* relationship.shipment start */
  test(resourceType + '.shipment', async () => {
    const id = TestData.id
    const params = { fields: { shipments: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'shipment')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .shipment(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.shipment stop */

  /* relationship.line_item start */
  test(resourceType + '.line_item', async () => {
    const id = TestData.id
    const params = { fields: { line_items: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'line_item')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .line_item(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.line_item stop */

  /* relationship.stock_item start */
  test(resourceType + '.stock_item', async () => {
    const id = TestData.id
    const params = { fields: { stock_items: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'stock_item')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .stock_item(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.stock_item stop */

  /* relationship.sku start */
  test(resourceType + '.sku', async () => {
    const id = TestData.id
    const params = { fields: { skus: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'sku')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .sku(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.sku stop */

  /* relationship.stock_reservation start */
  test(resourceType + '.stock_reservation', async () => {
    const id = TestData.id
    const params = { fields: { stock_reservations: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'stock_reservation')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .stock_reservation(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.stock_reservation stop */

  /* relationship.event_stores start */
  test(resourceType + '.event_stores', async () => {
    const id = TestData.id
    const params = { fields: { event_stores: CommonData.paramsFields } }

    const _intId = cl.addRequestInterceptor((request) => {
      expect(request.options.method).toBe('GET')
      checkCommon(request, resourcePath, id, currentAccessToken, 'event_stores')
      checkCommonParams(request, params)
      return interceptRequest()
    })

    await shipment_line_items
      .event_stores(id, params, CommonData.options)
      .catch(handleError)
      .finally(() => cl.removeInterceptor('request'))
  })
  /* relationship.event_stores stop */
})
