
// import * as api from './api'
import type { ResourceTypeLock } from './api'
import type { ApiError } from './error'
import type { ErrorInterceptor, InterceptorType, RawResponseReader, RequestInterceptor, ResponseInterceptor, ResponseObj, HeadersObj, InterceptorManager } from './interceptor'
import { CommerceLayerStatic } from './static'
import ResourceAdapter, { ApiResourceAdapter, type ResourcesInitConfig } from './resource'


import Debug from './debug'
const debug = Debug('commercelayer')


// Autogenerated schema version number, do not remove this line
const OPEN_API_SCHEMA_VERSION = '7.8.2'
export { OPEN_API_SCHEMA_VERSION }


// SDK local configuration
type SdkConfig = {
	// abc?: string
}

type CommerceLayerInitConfig = SdkConfig & ResourcesInitConfig
type CommerceLayerConfig = Partial<CommerceLayerInitConfig>



class CommerceLayerClient {

	static get openApiSchemaVersion(): string { return OPEN_API_SCHEMA_VERSION }
	readonly openApiSchemaVersion = OPEN_API_SCHEMA_VERSION

	readonly #adapter: ResourceAdapter
	// #slug: string

	// ##__CL_RESOURCES_DEF_START__##
	// ##__CL_RESOURCES_DEF_TEMPLATE:: ##__TAB__#####__RESOURCE_TYPE__##?: api.##__RESOURCE_CLASS__##
	// ##__CL_RESOURCES_DEF_STOP__##


	constructor(config: CommerceLayerInitConfig) {

		debug('new commercelayer instance %O', config)

		this.#adapter = ApiResourceAdapter.init(config) // new ResourceAdapter(config)
		// this.#slug = config.organization ?? ''

		// ##__CL_RESOURCES_INIT_START__##
		// ##__CL_RESOURCES_INIT_TEMPLATE:: ##__TAB__####__TAB__##this.##__RESOURCE_TYPE__## = new api.##__RESOURCE_CLASS__##(this.#adapter)
		// ##__CL_RESOURCES_INIT_STOP__##

	}

	// ##__CL_RESOURCES_LEAZY_LOADING_START__##
	// ##__CL_RESOURCES_LEAZY_LOADING_TEMPLATE:: ##__TAB__##get ##__RESOURCE_TYPE__##(): api.##__RESOURCE_CLASS__## { return this.###__RESOURCE_TYPE__## || (this.###__RESOURCE_TYPE__## = new api.##__RESOURCE_CLASS__##(this.#adapter)) }
	// ##__CL_RESOURCES_LEAZY_LOADING_STOP__##

	
	get currentOrganization(): string { return this.#adapter?.client?.currentOrganization }
	get currentAccessToken(): string { return this.#adapter?.client?.currentAccessToken }
	private get interceptors(): InterceptorManager { return this.#adapter.client.interceptors }


	private localConfig(config: Partial<SdkConfig> & { organization?: string }): void {
		// if (config.organization) this.#slug = config.organization
	}


	config(config: CommerceLayerConfig): this {

		debug('config %o', config)

		// CommerceLayer config
		this.localConfig(config)
		// ResourceAdapter config
		// To rebuild baseUrl in client in case only the domain is defined
		// if (!config.organization) config.organization = this.currentOrganization
		this.#adapter.config(config)

		return this

	}

	
	resources(): readonly string[] {
		return CommerceLayerStatic.resources()
	}

	singletons(): readonly string[] {
		return CommerceLayerStatic.singletons()
	}

	isSingleton(resource: ResourceTypeLock): boolean {
		return CommerceLayerStatic.isSingleton(resource)
	}
	

	isApiError(error: any): error is ApiError {
		return CommerceLayerStatic.isApiError(error)
	}


	addRequestInterceptor(onSuccess?: RequestInterceptor, onFailure?: ErrorInterceptor): number {
		this.interceptors.request = { onSuccess, onFailure }
		return 1
	}

	addResponseInterceptor(onSuccess?: ResponseInterceptor, onFailure?: ErrorInterceptor): number {
		this.interceptors.response = { onSuccess, onFailure }
		return 1
	}

	removeInterceptor(type: InterceptorType, id: number = 1): void {
		this.interceptors[type] = undefined
	}

	removeInterceptors(): void {
		this.removeInterceptor('request')
		this.removeInterceptor('response')
		this.removeRawResponseReader()
	}

	addRawResponseReader(options?: { headers: boolean }): RawResponseReader {

		const reader: RawResponseReader = {
			id: 0,
			rawResponse: undefined,
			headers: undefined,
			ok: true
		}

		async function rawResponseInterceptor(response: ResponseObj): Promise<ResponseObj> {
			reader.rawResponse = await response?.clone().json().catch(() => {})
			reader.ok = response.ok
			if (options?.headers) {
				const ho: HeadersObj = {}
				response.headers.forEach((value, key) => { ho[key] = value })
				reader.headers = ho
			}
			return response
		}
		
		/* const interceptor = */this.interceptors.rawReader = { onSuccess: rawResponseInterceptor, onFailure: rawResponseInterceptor }
		reader.id = 1 // interceptor

		return reader

	}

	removeRawResponseReader(/* reader: number | RawResponseReader */): void {
		/*
		const id = (typeof reader === 'number') ? reader : reader?.id
		if (id && (id >= 0)) this.removeInterceptor('response', id)
		*/
		this.interceptors.rawReader = undefined
	}

}



const CommerceLayer = (config: CommerceLayerInitConfig): CommerceLayerClient => {
	return new CommerceLayerClient(config)
}


export default CommerceLayer
export { CommerceLayer }

export type { CommerceLayerClient, CommerceLayerConfig, CommerceLayerInitConfig }
