import pkg from '../package.json' with { type: 'json' }

export const SDK_VERSION: string = pkg.version

// Autogenerated API schema version, do not remove this line
export const API_SCHEMA_VERSION: string = 'latest'
