name: Release
on:
  push:
    branches: [ main, sdk4, sdk5 ]
  pull_request:
    branches: [ main, sdk4, sdk5 ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run specs
        env:
          CL_SDK_ORGANIZATION: sdk-test-org
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release